settings:
  plush_list:
    - Ultralin
    - valdetutoriales
    - SeFirox
    - Shadoune777
    - YkaryD3ad
    - Divexel
    - KernelFreeze
    - xdemuux
    - Papuuchii__21
    - HolyHosting
    - 44KansuDeAru_
    - xDrygo
    - jose90MC
    - PixLewi
    - Dartus789
    - ImD4rken
    - SillyCriti
    - SunDiveser
    - _Vectorcin_
    - iadriano_
    - polentaentangada
    - Kendo_MC
    - IvanexDeYoshino
    - BrunoNashe_
    - DarkWitch
    - ATR3X_
    - iMetr1x
    - BurritoRiv
    - Fepo5302
    - SunnyMP
    - gatilgo
    - Darck97